' CTRL+SHIFT+X to export
' CTRL+SHIFT+W to preview

@startuml class-diagram

' Entities

class Page {
    - title: string
    - isCommentAllowed: boolean
    - isActive: boolean
}

class Article {
    - title: string
    - author: User
    - isCommentAllowed: boolean
    - isActive: boolean
}

class PageBlock {
    - page: Page
    - block: Block
    - column: integer
}

class ArticleBlock {
    - article: Article
    - block: Block
}

class BlockType {
    - name: string
    - isActive: boolean
}

class BlockTypeInterface {
    - name: string
    - isActive: boolean
}

class Comment {
    - title: string
    - content: text
    - article: Article
    - author: User
    - isActive: boolean
}

class User {
    - username: string
    - email: string
    - name: string
    - lastname: string
    - birthday: date
    - password: string
    - isActive: boolean
}

class Role {
    - name: string
    - isActive: boolean
}

' Relations
Article "One" *-- "Many" Comment : has >
Page "One" *-- "Many" Comment : has >
User "One" *-- "Many" Article : write >
User "One" *- "Many" Comment : write >
User "Many" -* "One" Role : has >
Page "One" *-- "Many" PageBlock : has >
' Article "One" *-- "Many" Block : has >
' Block "One" -- "One" BlockType


@enduml