version: '3'

services:
    

    postgres:
        image: postgres:13.1
        container_name: clean_arch_postgres
        hostname: clean_arch_postgres
        restart: always
        environment:
            - DATABASE_HOST=postgres
            - POSTGRES_DB=clean_arch_postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5400:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    mailer:
        image:  maildev/maildev
        container_name: "sf_maildev"
        command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
        ports: [1025, 1080]

volumes: 
     postgres-data: